export const copy = {
  module: "Personeel",
  collega: "Collega",
  collegas: "Collega's",
  zoekCollega: "Zoek collega…",
  wanneer: "Wanneer kom je?",
  waarSlaap: "Waar slaap je?",
  meerDetails: "Meer details",
  geenPlanning: "Nog geen planning",
  vandaagAanHetWerk: "Wie werkt er vandaag",
  mijnPlanning: "Mijn planning",
  vandaag: "Vandaag",
  tijdlijn: "Tijdlijn",
  wonen: "Wonen",
  settings: "Beheer",
  nieuweCollega: "Nieuwe collega",
  bewerken: "Bewerken",
  verwijderen: "Verwijderen",
  annuleren: "Annuleren",
  opslaan: "Opslaan",
  naam: "Naam",
  vestiging: "Vestiging",
  team: "Team",
  slaapplek: "Slaapplek",
  startDatum: "Startdatum",
  eindDatum: "Einddatum",
  dagenPerWeek: "Dagen per week",
  competentie: "Competentie",
  betaling: "Betaling",
  notities: "Notities",
  huidig: "Huidig",
  toekomstig: "Toekomstig",
  verleden: "Verleden",
  weet_je_zeker: "Weet je het zeker?",
  archiveer_uitleg: "De collega wordt gearchiveerd. Je kunt dit niet zelf ongedaan maken.",
  vandaag_knop: "Vandaag",
  geen_actief_planning: "Nu niemand actief",
  capaciteit: "Capaciteit",
  bewoners: "Bewoners",
  overboekt: "Overboekt",
  opslaan_gelukt: "Opgeslagen",
  opslaan_mislukt: "Opslaan mislukt — probeer opnieuw",
  verwijderen_mislukt: "Verwijderen mislukt — collega is teruggezet",
  wis_filters: "Wis filters",
  zoek: "Zoek",
} as const;
