// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { hybridAuthStorage } from './sessionStorage';
import { supabaseFetch } from './fetchWithBackoff';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    // Hybrid IndexedDB + localStorage adapter — survives Safari/iPadOS
    // storage cleanup better than localStorage alone.
    storage: hybridAuthStorage,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
    flowType: 'pkce',
    storageKey: 'puravida-auth',
  },
  global: {
    // Backoff/retry on 429/5xx + dedupe of concurrent refresh_token calls.
    fetch: supabaseFetch,
  },
});
